OWB-938 catching NoClassDefFoundError everywhere isValidManagedBean is called
git-svn-id: https://svn.apache.org/repos/asf/openwebbeans/trunk@1575368 13f79535-47bb-0310-9956-ffa450edef68