[OWB-442] since our EJB proxies only implement 1 of n interfaces, we need to create a unique proxy class per injected local interface for each EJB Class / Enterprise bean, otherwise a 2nd interface injection is incompatible with the proxy.
java.lang.IllegalArgumentException: Can not set org.apache.webbeans.sample.ejb.OtherIface field org.apache.webbeans.sample.bean.EchoManaged.echo3 to org.apache.webbeans.sample.ejb.Echo_$$_javassist_3




git-svn-id: https://svn.apache.org/repos/asf/openwebbeans/trunk@987154 13f79535-47bb-0310-9956-ffa450edef68